# Generated by Django 5.1.3 on 2024-12-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedtask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
